apiVersion: helm.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: production
spec:
  releaseName: rabbitmq-production
  chart:
    git: git@github.com:sweanan/arc-k8s-demo.git
    path: helm/rabbitmq
    ref: main
  values:
    image:
      repository: sweanan/arc-k8s-demo
      tag: production
    replicaCount: 2
    env:
      name: MESSAGE
      value: Azure Arc enabled K8s GitOps Demo!
