apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: production
spec:
  releaseName: production-0
  chart:
    git: https://github.com/sweanan/arc-k8s-demo.git
    path: ./helm/rabbitmq
    ref: main
  values:
    image:
      registry: docker.io
      repository: bitnami/rabbitmq
      tag: 3.9.13-debian-10-r38
    replicaCount: 2
    env:
      name: MESSAGE
      value: Azure Arc enabled K8s GitOps Demo!
